"""add new filed

Revision ID: 62b60c60f48c
Revises: d1503b35baf3
Create Date: 2024-11-17 18:18:45.186571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b60c60f48c'
down_revision: Union[str, None] = 'd1503b35baf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codeforces_problem', sa.Column('id_in_mongodb', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codeforces_problem', 'id_in_mongodb')
    # ### end Alembic commands ###
