"""add

Revision ID: 70838a044207
Revises: 70537dd414f4
Create Date: 2024-11-16 13:32:21.889502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70838a044207'
down_revision: Union[str, None] = '70537dd414f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codeforces_problem', sa.Column('solved_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codeforces_problem', 'solved_count')
    # ### end Alembic commands ###
