"""update user table

Revision ID: 898679a4fa4f
Revises: 1b4dcf859716
Create Date: 2024-08-15 19:15:12.234149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '898679a4fa4f'
down_revision: Union[str, None] = '1b4dcf859716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('codeforcesname', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('codeforcesrating', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('codeforcessloved', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('nowcodername', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('nowcoderrating', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('nowcodersloved', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('atcodername', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('atcoderrating', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('atcodersloved', sa.BigInteger(), nullable=True))
    op.drop_column('user', 'codeforcesid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('codeforcesid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_column('user', 'atcodersloved')
    op.drop_column('user', 'atcoderrating')
    op.drop_column('user', 'atcodername')
    op.drop_column('user', 'nowcodersloved')
    op.drop_column('user', 'nowcoderrating')
    op.drop_column('user', 'nowcodername')
    op.drop_column('user', 'codeforcessloved')
    op.drop_column('user', 'codeforcesrating')
    op.drop_column('user', 'codeforcesname')
    # ### end Alembic commands ###
