"""Initial migration

Revision ID: 995a04d1cf9e
Revises: 70838a044207
Create Date: 2024-11-16 14:05:10.536713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '995a04d1cf9e'
down_revision: Union[str, None] = '70838a044207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('codeforces_problem', 'rating',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('codeforces_problem', 'rating',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
