"""Initial migration

Revision ID: d1503b35baf3
Revises: 995a04d1cf9e
Create Date: 2024-11-16 14:12:14.948235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1503b35baf3'
down_revision: Union[str, None] = '995a04d1cf9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_contest_id_index', 'codeforces_problem', ['contest_id', 'index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_contest_id_index', table_name='codeforces_problem')
    # ### end Alembic commands ###
