"""initial migration

Revision ID: e33e01a2c886
Revises: 
Create Date: 2024-07-27 16:34:11.773561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = 'e33e01a2c886'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def table_exists(table_name):
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    return table_name in inspector.get_table_names()

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hash_id', sa.String(length=50), nullable=True),
    sa.Column('code_url', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.Column('problem_id', sa.String(length=50), nullable=True),
    sa.Column('problem_title', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=50), nullable=True),
    sa.Column('verdict_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_problem_id', 'status', ['problem_id'], unique=False)
    op.create_index('idx_status_user_id', 'status', ['user_id'], unique=False)
    op.create_index(op.f('ix_status_code_url'), 'status', ['code_url'], unique=False)
    op.create_index(op.f('ix_status_hash_id'), 'status', ['hash_id'], unique=False)
    op.create_index(op.f('ix_status_problem_id'), 'status', ['problem_id'], unique=False)
    op.create_index(op.f('ix_status_problem_title'), 'status', ['problem_title'], unique=False)
    op.create_index(op.f('ix_status_user_id'), 'status', ['user_id'], unique=False)
    op.create_index(op.f('ix_status_verdict_id'), 'status', ['verdict_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.BigInteger(), nullable=True, comment='user authority'),
    sa.Column('codeforcesid', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    if table_exists('wronganswer_user'):
        op.drop_table('wronganswer_user')
        op.drop_index('wronganswer_status_code_url_4c7a3e1f', table_name='wronganswer_status')
        op.drop_index('wronganswer_status_hash_id_c9dd0dea', table_name='wronganswer_status')
        op.drop_index('wronganswer_status_problem_id_edda9251', table_name='wronganswer_status')
        op.drop_index('wronganswer_status_problem_title_82ba5295', table_name='wronganswer_status')
        op.drop_index('wronganswer_status_user_id_3dbff879', table_name='wronganswer_status')
        op.drop_index('wronganswer_status_verdict_id_7009433a', table_name='wronganswer_status')
        op.drop_table('wronganswer_status')
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wronganswer_status',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('when', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('problem_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('runtime', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('memory', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('verdict', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('verdict_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('visible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('language', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('hash_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('problem_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('wronganswer_status_verdict_id_7009433a', 'wronganswer_status', ['verdict_id'], unique=False)
    op.create_index('wronganswer_status_user_id_3dbff879', 'wronganswer_status', ['user_id'], unique=False)
    op.create_index('wronganswer_status_problem_title_82ba5295', 'wronganswer_status', ['problem_title'], unique=False)
    op.create_index('wronganswer_status_problem_id_edda9251', 'wronganswer_status', ['problem_id'], unique=False)
    op.create_index('wronganswer_status_hash_id_c9dd0dea', 'wronganswer_status', ['hash_id'], unique=False)
    op.create_index('wronganswer_status_code_url_4c7a3e1f', 'wronganswer_status', ['code_url'], unique=False)
    op.create_table('wronganswer_user',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('role', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codeforcesid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    op.drop_index(op.f('ix_status_verdict_id'), table_name='status')
    op.drop_index(op.f('ix_status_user_id'), table_name='status')
    op.drop_index(op.f('ix_status_problem_title'), table_name='status')
    op.drop_index(op.f('ix_status_problem_id'), table_name='status')
    op.drop_index(op.f('ix_status_hash_id'), table_name='status')
    op.drop_index(op.f('ix_status_code_url'), table_name='status')
    op.drop_index('idx_status_user_id', table_name='status')
    op.drop_index('idx_status_problem_id', table_name='status')
    op.drop_table('status')
    # ### end Alembic commands ###
