"""add new table

Revision ID: e7308fc254a1
Revises: 86bc6e138d76
Create Date: 2024-11-17 19:25:02.717449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7308fc254a1'
down_revision: Union[str, None] = '86bc6e138d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codeforces_problem',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('contest_index', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('solved_count', sa.Integer(), nullable=False),
    sa.Column('id_in_mongodb', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contest_id_index', 'codeforces_problem', ['contest_id', 'contest_index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_contest_id_index', table_name='codeforces_problem')
    op.drop_table('codeforces_problem')
    # ### end Alembic commands ###
